name: Test Santa

description: "Santa is secret"

on:
  push

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install project
      shell: bash
      run: |
        make install
        make fmt

    - name: Test project
      shell: bash
      run: |
        make test
