# Workflow for testing the Docker container
# This workflow ensures the Docker container builds and runs correctly

name: Docker Test

# Trigger the workflow on push events and pull requests
on:
  push:
    paths:
      - 'docker/**'
      - 'app.py'
      - 'pysanta/**'
      - 'requirements.txt'
      - '.github/workflows/docker-test.yml'
  pull_request:
    paths:
      - 'docker/**'
      - 'app.py'
      - 'pysanta/**'
      - 'requirements.txt'
      - '.github/workflows/docker-test.yml'

jobs:
  # Job to test the Docker container
  docker-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Test with script
      - name: Test with script
        run: |
          # you have to be in the correct folder
          cd docker
          ./test_docker.sh
