name: pre-commit

on:
  push:

permissions:
  contents: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tschm/cradle:v0.1.65
      options: --user 0

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - name: Introduce python
        run: |
          ln -s python3 python

      - uses: tschm/cradle/actions/pre-commit@v0.1.65
