name: pre-commit

on:
  push:

permissions:
  contents: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tschm/cradle:latest
      #options: --user 0

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      #- name: Introduce python
      #  shell: bash
      #  run: |
      #    ln -s /usr/bin/python3 python
      #    python --version

      #- uses: tschm/cradle/actions/pre-commit@v0.1.65
      - name: Install deps
        run: pip3 install pre-commit

      - name: Run pre-commit
        run: |
          pwd
          ls -all
          pre-commit run --show-diff-on-failure --color=always --verbose --all-files