# Workflow for running pre-commit checks on code
# This workflow ensures code quality and consistency

name: pre-commit

# Trigger the workflow on push events
on:
  push:

# Set permissions to write to repository contents (if needed for auto-fixes)
permissions:
  contents: write

jobs:
  # Job to run pre-commit hooks on all files
  pre-commit:
    runs-on: ubuntu-latest
    # Commented out container configuration (alternative execution environment)
    steps:
      # Check out the repository code
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      # Run pre-commit checks using the cradle action
      - uses: tschm/cradle/actions/pre-commit@v0.1.69
