# Workflow for creating a new version release and building a Docker image
# This workflow is manually triggered to create a new version tag and build a Docker image

name: Bump version

# Trigger the workflow manually using the GitHub Actions UI
on:
  workflow_dispatch

jobs:
  # Job to generate a new version tag
  tagging:
    # Permission to write to repository contents (create tags)
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}  # This will output the tag for other jobs
    steps:
      # Generate a new version tag based on semantic versioning
      - name: Generate Tag
        id: tag_version
        uses: tschm/cradle/actions/tag@v0.1.69
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Output the generated tag for debugging purposes
      - name: Debug Output Tag
        run: |
            echo "Tag: ${{ steps.tag_version.outputs.new_tag }}"

  page:
    needs: tagging
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Convert notebook to HTML
        run: |
          uv run pip install --no-cache-dir marimo
          mkdir -p artifacts/marimo
          uv run marimo export html app.py -o artifacts/marimo/index.html

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: artifacts/


  # Job to deploy the built book to GitHub Pages
  deploy-book:
    runs-on: ubuntu-latest
    # This job depends on both jupyter and marimo jobs completing successfully
    needs: page
    # Need write permission to push to gh-pages branch
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
