name: Bump version

on:
  workflow_dispatch

jobs:
  tagging:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}  # This will output the tag for other jobs
    steps:
      - name: Generate Tag
        id: tag_version
        uses: tschm/cradle/actions/tag@v0.1.55
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_package: 'false'

      - name: Debug Output Tag
        run: |
            echo "Tag: ${{ steps.tag_version.outputs.new_tag }}"

  docker:
    needs: tagging
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      # -----------------------------------------------------------------------------
      # Step 1: Checkout the repository
      # -----------------------------------------------------------------------------
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - name: Build and Push Docker Image
        uses: tschm/cradle/actions/docker@main
        with:
          github_repository: ${{ github.repository }}
          tag: ${{ needs.tagging.outputs.new_tag }}
          #dockerfile-path: 'docker/Dockerfile'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_actor: ${{ github.actor }}
