# Workflow for creating a new version release and building a Docker image
# This workflow is manually triggered to create a new version tag and build a Docker image

name: Bump version

# Trigger the workflow manually using the GitHub Actions UI
on:
  workflow_dispatch

jobs:
  # Job to generate a new version tag
  tagging:
    # Permission to write to repository contents (create tags)
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}  # This will output the tag for other jobs
    steps:
      # Generate a new version tag based on semantic versioning
      - name: Generate Tag
        id: tag_version
        uses: tschm/cradle/actions/tag@v0.1.69
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Output the generated tag for debugging purposes
      - name: Debug Output Tag
        run: |
            echo "Tag: ${{ steps.tag_version.outputs.new_tag }}"

  page:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.69

      - uses: Convert notebook to HTML
        run: |
          @uv run pip install marimo
          @mkdir -p artifacts/marimo
          @uv run marimo export html app.py -o artifacts/marimo/index.html

      - name: GitHub Pages action
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages            # The branch the action should deploy to.
          folder: artifacts/marimo               # The folder the action should deploy.
