# Workflow for creating a new version release and building a Docker image
# This workflow is manually triggered to create a new version tag and build a Docker image

name: Bump version

# Trigger the workflow manually using the GitHub Actions UI
on:
  workflow_dispatch

jobs:
  # Job to generate a new version tag
  tagging:
    # Permission to write to repository contents (create tags)
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}  # This will output the tag for other jobs
    steps:
      # Generate a new version tag based on semantic versioning
      - name: Generate Tag
        id: tag_version
        uses: tschm/cradle/actions/tag@v0.1.64
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Output the generated tag for debugging purposes
      - name: Debug Output Tag
        run: |
            echo "Tag: ${{ steps.tag_version.outputs.new_tag }}"

  # Job to build and push a Docker image with the new version tag
  docker:
    # This job depends on the tagging job
    needs: tagging
    # Permissions to read repository contents and write to GitHub Packages
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      # -----------------------------------------------------------------------------
      # Step 1: Checkout the repository
      # -----------------------------------------------------------------------------
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      # Build and push the Docker image with the new tag
      - name: Build and Push Docker Image
        uses: tschm/cradle/actions/docker@v0.1.64
        with:
          github_repository: ${{ github.repository }}  # Repository to build the image for
          tag: ${{ needs.tagging.outputs.new_tag }}    # Tag from the tagging job
          github_token: ${{ secrets.GITHUB_TOKEN }}    # Token for authentication
          github_actor: ${{ github.actor }}            # Current user
          dockerfiles: 'docker/Dockerfile'             # Path to the Dockerfile
