# Workflow for creating a new version release and deploying to GitHub Pages
# This workflow is manually triggered to:
# 1. Create a new version tag using semantic versioning
# 2. Convert the Marimo notebook to HTML
# 3. Deploy the HTML to GitHub Pages

name: Bump version

# Trigger the workflow manually using the GitHub Actions UI
# This allows controlled releases when needed rather than on every push
on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  # Job to generate a new version tag based on semantic versioning
  # This creates a new git tag with an incremented version number
  tagging:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      # This output variable makes the tag available to other jobs in the workflow
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      # Use the cradle/actions/tag action to generate a semantic version tag
      # This automatically determines the next version number based on commit messages
      - name: Generate Tag
        id: tag_version
        uses: tschm/cradle/actions/tag@v0.1.75
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Output the generated tag for debugging and verification purposes
      - name: Debug Output Tag
        run: |
            echo "Tag: ${{ steps.tag_version.outputs.new_tag }}"

  # Job to build the HTML page from the Marimo notebook
  # This job converts the app.py Marimo notebook to HTML and prepares it for deployment
  # The build job exports marimo notebooks to static HTML/WebAssembly
  marimo:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    needs: tagging
    steps:
      - uses: jebel-quant/marimushka@v0.1.3
        with:
          apps: 'apps'

  book:
    runs-on: ubuntu-latest
    needs: marimo

    environment:
      name: github-pages

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: tschm/cradle/actions/book@v0.1.75
